require 'pry'
require 'action_view'
require 'action_controller'
require 'htmlbeautifier'
require 'slim/erb_converter'
require 'active_support/core_ext/hash/deep_merge'
require 'active_support/core_ext/string/starts_ends_with'
require 'pagy'

Dir.glob(File.join('./lib', '**', '*.rb')).sort.each { |f| require f }

use_helper Nanoc::Helpers::Rendering
use_helper Nanoc::Helpers::LinkTo
use_helper Nanoc::Helpers::XMLSitemap
use_helper Helpers::LinkHelpers
use_helper Helpers::TitleAnchorHelpers
use_helper Helpers::Formatters
use_helper Helpers::ContentHelpers

$LOAD_PATH.unshift(File.expand_path("../../app", "app"))
$LOAD_PATH.unshift(File.expand_path("../../lib", "lib"))

require 'dsfr/components'

require 'components/dsfr_component'
require 'components/dsfr_component/traits'
require 'components/dsfr_component/traits/custom_html_attributes'
require 'components/dsfr_component/base'
require 'components/dsfr_component/accordion_component'
require 'components/dsfr_component/accordion_component/section_component'
require 'components/dsfr_component/back_link_component'
require 'components/dsfr_component/breadcrumbs_component'
require 'components/dsfr_component/cookie_banner_component'
require 'components/dsfr_component/cookie_banner_component/message_component'
require 'components/dsfr_component/details_component'
require 'components/dsfr_component/footer_component'
require 'components/dsfr_component/header_component'
require 'components/dsfr_component/inset_text_component'
require 'components/dsfr_component/notification_banner_component'
require 'components/dsfr_component/pagination_component'
require 'components/dsfr_component/pagination_component/item'
require 'components/dsfr_component/pagination_component/adjacent_page'
require 'components/dsfr_component/pagination_component/next_page'
require 'components/dsfr_component/pagination_component/previous_page'
require 'components/dsfr_component/panel_component'
require 'components/dsfr_component/phase_banner_component'
require 'components/dsfr_component/section_break_component'
require 'components/dsfr_component/start_button_component'
require 'components/dsfr_component/summary_list_component'
require 'components/dsfr_component/summary_list_component/key_component'
require 'components/dsfr_component/summary_list_component/value_component'
require 'components/dsfr_component/summary_list_component/action_component'
require 'components/dsfr_component/summary_list_component/row_component'
require 'components/dsfr_component/table_component'
require 'components/dsfr_component/table_component/cell_component'
require 'components/dsfr_component/table_component/caption_component'
require 'components/dsfr_component/table_component/head_component'
require 'components/dsfr_component/table_component/body_component'
require 'components/dsfr_component/table_component/row_component'
require 'components/dsfr_component/tab_component'
require 'components/dsfr_component/tag_component'
require 'components/dsfr_component/warning_text_component'

require 'helpers/dsfr_link_helper'

use_helper DsfrLinkHelper
use_helper DsfrComponentsHelper
use_helper Examples::LinkHelpers
use_helper Examples::AccordionHelpers
use_helper Examples::BreadcrumbsHelpers
use_helper Examples::BackLinkHelpers
use_helper Examples::CookieBannerHelpers
use_helper Examples::DetailsHelpers
use_helper Examples::FooterHelpers
use_helper Examples::HeaderHelpers
use_helper Examples::InsetTextHelpers
use_helper Examples::NotificationBannerHelpers
use_helper Examples::PaginationHelpers
use_helper Examples::PanelHelpers
use_helper Examples::PhaseBannerHelpers
use_helper Examples::SectionBreakHelpers
use_helper Examples::SkipLinkHelpers
use_helper Examples::StartButtonHelpers
use_helper Examples::SummaryListHelpers
use_helper Examples::TableHelpers
use_helper Examples::TabsHelpers
use_helper Examples::TagHelpers
use_helper Examples::WarningTextHelpers
use_helper Examples::CommonOptionsHelpers
use_helper Examples::BackToTopLinkHelpers
